s/Master configuration file/DO NOT EDIT THIS FILE - EDIT MASTER/
s/MACHINE/vax/
s/CPU-TYPES/cpu	"VAX8600"\
cpu	"VAX780"\
cpu	"VAXM"\
cpu	"KA820"/
s/TIMEZONE/5 dst/
s/MAXUSERS/50/
s/MAXCPUS/16/
/^options		MACH_TIME/d
s/# PSEUDO-DEVICES/pseudo-device	mach_mpm 4\
pseudo-device	cmupty\
pseudo-device	fe 3\
pseudo-device	ild/
