s/Master configuration file/DO NOT EDIT THIS FILE - EDIT MASTER/
s/MACHINE/vax/
s/CPU-TYPES/cpu	"VAX8600"\
cpu	"VAX780"\
cpu	"VAXM"\
cpu	"KA820"/
s/TIMEZONE/5 dst/
s/MAXUSERS/16/
s/MAXCPUS/1/
s/# PSEUDO-DEVICES/pseudo-device	mach_mpm 4/
