/*
 ****************************************************************
 * Mach Operating System
 * Copyright (c) 1986 Carnegie-Mellon University
 *  
 * This software was developed by the Mach operating system
 * project at Carnegie-Mellon University's Department of Computer
 * Science. Software contributors as of May 1986 include Mike Accetta, 
 * Robert Baron, William Bolosky, Jonathan Chew, David Golub, 
 * Glenn Marcy, Richard Rashid, Avie Tevanian and Michael Young. 
 * 
 * Some software in these files are derived from sources other
 * than CMU.  Previous copyright and other source notices are
 * preserved below and permission to use such software is
 * dependent on licenses from those institutions.
 * 
 * Permission to use the CMU portion of this software for 
 * any non-commercial research and development purpose is
 * granted with the understanding that appropriate credit
 * will be given to CMU, the Mach project and its authors.
 * The Mach project would appreciate being notified of any
 * modifications and of redistribution of this software so that
 * bug fixes and enhancements may be distributed to users.
 *
 * All other rights are reserved to Carnegie-Mellon University.
 ****************************************************************
 */
/***********************************************************************
 *
 * Genassym.c - Program to generate a proc.m file for locore.
 *
 ***********************************************************************
 * HISTORY
 *  8-Apr-86  Bill Bolosky (bolosky) at Carnegie-Mellon University
 *	MACH_VM: Added extra symbols to allow load_context to grab the
 *	segment registers out of the pmap.
 *
 *  7-Mar-86  Bill Bolosky (bolosky) at Carnegie-Mellon University
 *	Created.
 *
 ***********************************************************************
 */

#include "../h/types.h"
#include "../h/param.h"
#include "../h/dir.h"
#include "../h/user.h"
#include "../h/proc.h"
#include "mach_vm.h"
#if	MACH_VM
#include "../h/thread.h"
#include "../h/task.h"
#include "../vm/vm_map.h"
#include "../ca/pmap.h"
#include "../ca/pcb.h"
thread_t	active_threads[1];
#endif	MACH_VM

main()
{
 register struct user *u = (struct user *)0;
 register struct proc *p = (struct proc *)0;
#if	MACH_VM
 struct thread *th = (struct thread *)0;
 struct task *ta = (struct task *)0;
 vm_map_t ma = (vm_map_t) 0;
 struct pmap *pm = (struct pmap *)0;
 struct pcb *pcb = (struct pcb *)0;
#endif	MACH_VM 

 printf("/* This proc.m file was generated by genassym for Mach on the RT. */\n");

 printf("#ifdef LOCORE\n");
 printf(".set P_ADDR , %d\n",&p->p_addr);
 printf(".set P_CPU , %d\n",&p->p_cpu);
 printf(".set P_LINK , %d\n",&p->p_link);
 printf(".set P_PRI , %d\n",&p->p_pri);
 printf(".set P_P0BR , %d\n",&p->p_p0br);
 printf(".set P_RLINK , %d\n",&p->p_rlink);
 printf(".set P_SID0 , %d\n",&p->p_sid0);
 printf(".set P_SID1 , %d\n",&p->p_sid1);
 printf(".set P_STAT , %d\n",&p->p_stat);
 printf(".set P_SZPT , %d\n",&p->p_szpt);
 printf(".set P_USRPRI , %d\n",&p->p_usrpri);
 printf(".set P_PID , %d\n",&p->p_pid);
 printf(".set SRUN , %d\n",SRUN);
 printf(".set SZOMB , %d\n",SZOMB);
 printf(".set U_PROCP , %d\n",&u->u_procp);
#if	MACH_VM
 printf(".set THREAD_PCB , %d\n",&th->pcb);
 printf(".set THREAD_TASK , %d\n",&th->task);
 printf(".set TASK_MAP , %d\n",&ta->map);
 printf(".set MAP_PMAP , %d\n",&ma->pmap);
 printf(".set PMAP_SIDTAB , %d\n",pm->sidtab);
 printf(".set PCB_R14 , %d\n",&pcb->pcb_r14);
#endif	MACH_VM
 printf(".set USIZE , 0x%x\n",sizeof(struct user));
 printf("#endif LOCORE\n");
}
